# city list
city_list = ["sari" , "nowshahr" , "noor" , "chalous" , "ramsar" , "namakabrood"]
print(city_list[+0])
print(city_list[+5])
print(city_list[+4])
print(city_list[-3])
print(city_list[-1])
print(city_list[-0])
city_list.extend("nowshahr")
print(city_list)
city_list.remove("sari")
print(city_list)
city_list.append("lahijan")
print(city_list)
city_list.insert(3 , "nowshahr")
print(city_list)
city_list.pop(1)
print(city_list)
print(len(city_list))
